### ISSUE TITLE
Segmentation Fault when SharedUsers are added

### ISSUE THREAD

**Issue by pddg** [pddg/ansible-octopass-role#1]
##  How to reproduce

```yaml
octopass_token: '{{ your token }}'
octopass_sharedusers:
  - deploy
```

Apply playbook, so the playbook generate following configuration.

```conf
Token = "{{ your token }}"
...
SharedUsers = ["deploy",]
```

Then, try to show `passwd` with octopass

```bash
$ sudo octopass passwd
Segmentation fault
```

## Why

`SharedUsers` section needs white space before `]`. This might be a bug of octopass.
